fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
#    user_class: App\Entity\Users
    user_class: App\Application\Sonata\UserBundle\Entity\User
    group:
#            group_class:   Sonata\UserBundle\Entity\BaseGroup
            group_class:   App\Application\Sonata\UserBundle\Entity\Group
            group_manager: sonata.user.orm.group_manager # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

    service:
            user_manager: sonata.user.orm.user_manager

    from_email:
        address: "vincent@vfac.fr"
        sender_name: "vincent@vfac.fr"
    registration:
            form:
                type: App\Services\RegistrationFormType