sonata_admin:
    security:
#    <<<<<<<<<<посмотреть здесь!!!!
#        handler: sonata.admin.security.handler.role

        role_admin: ROLE_USER
        role_super_admin: ROLE_SUPER_ADMIN

        # acl security information
#        information:
#             GUEST:    [VIEW, LIST]
#             STAFF:    [EDIT, LIST, CREATE]
#             EDITOR:   [OPERATOR, EXPORT]
#             ADMIN:    [MASTER]

        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
#        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
#         permission related to the objects
#        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    title: 'Админка'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
                            app.admin.group.content:
                                label: Контент
                                label_catalogue: App
                                items:
                                    - admin.jos.content
                                    - admin.description.key
                                roles: [ ROLE_STAFF ]
#                                roles: [ ROLE_USER ]
#                                roles: [ ROLE_ADMIN ]

                            app.admin.group.customer:
                                label: Users
                                label_catalogue: App
                                items:
                                    - admin.customer
#                                roles: [ ROLE_ADMIN ]
                                roles: [ ROLE_SUPER_ADMIN ]

                            app.admin.group.stat:
                                label: Статистика
                                label_catalogue: App
                                items:
                                    - admin.stat
                                    - admin.client.field
                                roles: [ ROLE_USER ]
#                                roles: [ ROLE_SUPER_ADMIN ]

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

services:

    admin.jos.content:
               class: App\Admin\JosContentAdmin
               arguments: [~, App\Entity\JosContent, ~]
               calls:
               ##                        - [setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
               ##                       - [setTranslationDomain, ['App']]
               #                      - [addChild, ['@admin.category', 'blogposts']]
                                     - [addChild, ['@admin.description.key', 'content']]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: О компании, label_catalogue: App }
               public: true

    admin.customer:
               class: App\Admin\CustomerAdmin
               arguments: [~, App\Entity\Customer, ~]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: User, roles: ROLE_SUPER_ADMIN, label_catalogue: App }
               public: true

    admin.description.key:
               class: App\Admin\DescriptionKeyAdmin
               arguments: [~, App\Entity\DescriptionKey, ~]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: Ключи, label_catalogue: App }
               public: true

    admin.stat:
               class: App\Admin\StatAdmin
               arguments: [~, App\Entity\Stat, ~]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: Статистика, label_catalogue: App }
               public: true

    admin.client.field:
               class: App\Admin\JosClientFieldsAdmin
               arguments: [~, App\Entity\JosClientFields, ~]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: Соц. сети, label_catalogue: App }
               public: true