sonata_admin:
    title: 'Админка'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
                            app.admin.group.content:
                                label: Контент
                                label_catalogue: App
                                items:
                                    - admin.jos.content
                                    - admin.description.key
#                                roles: [ ROLE_CUSTOMER ]
#                                roles: [ ROLE_USER ]

                            app.admin.group.customer:
                                label: Users
                                label_catalogue: App
                                items:
                                    - admin.customer
                                roles: [ ROLE_CUSTOMER ]
#                                roles: [ ROLE_SUPER_ADMIN ]

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

services:

    admin.jos.content:
               class: App\Admin\JosContentAdmin
               arguments: [~, App\Entity\JosContent, ~]
               calls:
               ##                        - [setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
               ##                       - [setTranslationDomain, ['App']]
               #                      - [addChild, ['@admin.category', 'blogposts']]
                                     - [addChild, ['@admin.description.key', 'content']]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: О компании, продукция и фото, label_catalogue: App }
               public: true

    admin.customer:
               class: App\Admin\CustomerAdmin
               arguments: [~, App\Entity\Customer, ~]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: User, label_catalogue: App }
               public: true

    admin.description.key:
               class: App\Admin\DescriptionKeyAdmin
               arguments: [~, App\Entity\DescriptionKey, ~]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: Ключи, label_catalogue: App }
               public: true