sonata_admin:
    security:
#    <<<<<<<<<<посмотреть здесь!!!!
#        handler: sonata.admin.security.handler.role

        role_admin: ROLE_USER
        role_super_admin: ROLE_SUPER_ADMIN

        # acl security information
#        information:
#             GUEST:    [VIEW, LIST]
#             STAFF:    [EDIT, LIST, CREATE]
#             EDITOR:   [OPERATOR, EXPORT]
#             ADMIN:    [MASTER]

        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
#        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
#         permission related to the objects
#        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    title: 'Админка'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
                            app.admin.group.content:
                                label: Контент
                                label_catalogue: App
                                items:
#                                    - admin.jos.content
#                                    - admin.description.key
                                    - admin.clients
                                    - admin.banners
                                roles: [ ROLE_STAFF ]
#                                roles: [ ROLE_USER ]
#                                roles: [ ROLE_ADMIN ]

                            app.admin.group.customer:
                                label: Users
                                label_catalogue: App
                                items:
                                    - admin.customer
#                                roles: [ ROLE_ADMIN ]
                                roles: [ ROLE_SUPER_ADMIN ]

                            app.admin.group.stat:
                                label: Админ. компаний
                                label_catalogue: App
                                items:
                                    - admin.client.field
                                    - admin.clients.land
                                    - admin.banners
                                    - admin.jos.rubric
                                    - admin.admin.clients
                                    - admin.categoryservice
                                    - admin.categoryproduct
                                    - admin.allreview
#                                    - admin.seotemplate
                                    - admin.clientsetting
#                                    - admin.newsletteradmin
                                roles: [ ROLE_ADMIN ]
#                                roles: [ ROLE_SUPER_ADMIN ]

                            app.admin.group.statOnly:
                                label: Статистика компаний
                                label_catalogue: App
                                items:
                                    - admin.stat
                                roles: [ ROLE_STAT_ONLY ]

                            app.admin.group.link:
                                label: Счетчик по ссылкам
                                label_catalogue: App
                                items:
                                    - admin.link
                                roles: [ ROLE_LINK_1, ROLE_LINK_2 ]

    show_mosaic_button: false
    templates:
            edit:   '@SonataAdmin/CRUD/base_edit_link.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

services:

    admin.jos.content:
               class: App\Admin\JosContentAdmin
               arguments: [~, App\Entity\JosContent, ~]
               calls:
               ##                        - [setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
               ##                       - [setTranslationDomain, ['App']]
               #                      - [addChild, ['@admin.category', 'blogposts']]
#                                     - [addChild, ['@admin.description.key', 'content']]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: О компании, label_catalogue: App }
               public: true

    admin.customer:
               class: App\Admin\CustomerAdmin
               arguments: [~, App\Entity\Customer, ~]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: User, roles: ROLE_SUPER_ADMIN, label_catalogue: App }
               public: true

    admin.description.key:
               class: App\Admin\DescriptionKeyAdmin
               arguments: [~, App\Entity\DescriptionKey, ~]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: Ключи, label_catalogue: App }
               public: true

    admin.stat:
               class: App\Admin\StatAdmin
               arguments: [~, App\Entity\Stat, ~]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: Статистика, label_catalogue: App }
               public: true

    admin.banners:
               class: App\Admin\JosBannersAdmin
               arguments: [~, App\Entity\JosBanners, ~]
               calls:
                   - [addChild, ['@admin.banners.key', 'josBanners']]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: Банера, label_catalogue: App }
               public: true

    admin.banners.key:
               class: App\Admin\BannersKeyAdmin
               arguments: [~, App\Entity\BannersKey, ~]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: Банера, label_catalogue: App }
               public: true

    admin.client.field:
               class: App\Admin\JosClientFieldsAdmin
               arguments: [~, App\Entity\JosClientFields, ~]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: Соц. сети, label_catalogue: App }
               public: true

    admin.clients.land:
               class: App\Admin\ClientsLandAdmin
               arguments: [~, App\Entity\ClientsLand, ~]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: Ссылка из рубрики на промо, label_catalogue: App }
               public: true

    admin.clients:
               class: App\Admin\CopirClientsAdmin
               arguments: [~, App\Entity\JosClientsKeywords, ~]
               calls:
                  - [addChild, ['@admin.jos.content', 'companytitle']]
                  - [addChild, ['@admin.description.key', 'company']]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: Список компаний, label_catalogue: App }
               public: true

    admin.admin.clients:
               class: App\Admin\AdminClientsAdmin
               arguments: [~, App\Entity\JosAdminClients, ~]
               calls:
#                  - [addChild, ['@admin.jos.content', 'companytitle2']]
                  - [addChild, ['@admin.clients', 'adminClients']]
                  - [addChild, ['@admin.tels', 'company']]
                  - [addChild, ['@admin.jos.rubric.client', 'company']]
                  - [addChild, ['@admin.newsletteradmin', 'company']]
                  - [addChild, ['@admin.sale', 'client']]
                  - [addChild, ['@admin.review', 'client']]
                  - [addChild, ['@admin.vacancy', 'company']]
                  - [addChild, ['@admin.product', 'company']]
                  - [addChild, ['@admin.service', 'company']]
                  - [addChild, ['@admin.filial', 'client']]
                  - [addChild, ['@admin.clientsetting', 'company']]
                  - [addChild, ['@admin.clientmetric', 'company']]
               tags:
                   - { name: sonata.admin, manager_type: orm, label: Компании, label_catalogue: App }
               public: true

    admin.link:
                   class: App\Admin\LinkClientsAdmin
                   arguments: [~, App\Entity\Link, ~]
                   tags:
                       - { name: sonata.admin, manager_type: orm, label: Ссылки, label_catalogue: App }
                   public: true

    admin.tels:
                   class: App\Admin\TelAdmin
                   arguments: [~, App\Entity\Tel, ~]
                   tags:
                       - { name: sonata.admin, manager_type: orm, label: Телефоны, label_catalogue: App }
                   public: true

    admin.jos.rubric.client:
                   class: App\Admin\JosRubricClientTestAdmin
                   arguments: [~, App\Entity\JosRubricClientTest, ~]
                   tags:
                       - { name: sonata.admin, manager_type: orm, label: Рубрики, label_catalogue: App }
                   public: true

    admin.jos.rubric:
                   class: App\Admin\JosRubricAdmin
                   arguments: [~, App\Entity\JosRubric, ~]
                   tags:
                        - { name: sonata.admin, manager_type: orm, label: Рубрики, label_catalogue: App }
                   public: true

    admin.newsletteradmin:
                   class: App\Admin\NewsletterAdmin
                   arguments: [~, App\Entity\NewsletterAdmin, ~]
                   tags:
                   - { name: sonata.admin, manager_type: orm, label: Новости, label_catalogue: App }
                   public: true
    admin.sale:
                   class: App\Admin\SaleAdmin
                   arguments: [~, App\Entity\SaleAdmin, ~]
                   tags:
                   - { name: sonata.admin, manager_type: orm, label: Акции, label_catalogue: App }
                   public: true
    admin.review:
                   class: App\Admin\ReviewAdmin
                   arguments: [~, App\Entity\ReviewAdmin, ~]
                   tags:
                   - { name: sonata.admin, manager_type: orm, label: Отзывы, label_catalogue: App }
                   public: true
    admin.vacancy:
                   class: App\Admin\VacancyAdmin
                   arguments: [~, App\Entity\VacancyAdmin, ~]
                   tags:
                   - { name: sonata.admin, manager_type: orm, label: Вакансии, label_catalogue: App }
                   public: true
    admin.categoryservice:
                    class: App\Admin\CategoryserviceAdmin
                    arguments: [~, App\Entity\CategoryserviceAdmin, ~]
                    tags:
                    - { name: sonata.admin, manager_type: orm, label: Категории услуг, label_catalogue: App }
                    public: true
    admin.categoryproduct:
                    class: App\Admin\CategoryproductAdmin
                    arguments: [~, App\Entity\CategoryproductAdmin, ~]
                    tags:
                    - { name: sonata.admin, manager_type: orm, label: Категории товаров, label_catalogue: App }
                    public: true
    admin.product:
                    class: App\Admin\ProductAdmin
                    arguments: [~, App\Entity\ProductAdmin, ~]
                    tags:
                    - { name: sonata.admin, manager_type: orm, label: Товары, label_catalogue: App }
                    public: true
    admin.service:
                    class: App\Admin\ServiceAdmin
                    arguments: [~, App\Entity\ServiceAdmin, ~]
                    tags:
                    - { name: sonata.admin, manager_type: orm, label: Услуги, label_catalogue: App }
                    public: true
    admin.allreview:
                    class: App\Admin\AllreviewAdmin
                    arguments: [~, App\Entity\AllreviewAdmin, ~]
                    tags:
                    - { name: sonata.admin, manager_type: orm, label: Все отзывы, label_catalogue: App }
                    public: true
    admin.seotemplate:
                    class: App\Admin\SeotemplateAdmin
                    arguments: [~, App\Entity\SeotemplateAdmin, ~]
                    tags:
                    - { name: sonata.admin, manager_type: orm, label: Шаблоны Meta, label_catalogue: App }
                    public: true
    admin.filial:
                    class: App\Admin\FilialAdmin
                    arguments: [~, App\Entity\FilialAdmin, ~]
                    tags:
                    - { name: sonata.admin, manager_type: orm, label: Филиалы, label_catalogue: App }
                    public: true
    admin.clientsetting:
                    class: App\Admin\ClientsettingAdmin
                    arguments: [~, App\Entity\ClientsettingAdmin, ~]
                    tags:
                    - { name: sonata.admin, manager_type: orm, label: Дополнительно, label_catalogue: App }
                    public: true
    admin.clientmetric:
                    class: App\Admin\ClientmetricAdmin
                    arguments: [~, App\Entity\ClientmetricAdmin, ~]
                    tags:
                    - { name: sonata.admin, manager_type: orm, label: Метрика, label_catalogue: App }
                    public: true